apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-2
  labels:
    tipo: deployment
    app: deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment2
      tier: backend
  template:
    metadata:
      labels:
        app: deployment2
        tier: backend            
    spec:
      affinity:
         nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - deployment1
      containers:
      - name: deployment2
        image: nginx:latest
        
   
      